os: linux-ppc64le
dist: xenial
sudo: false

#sudo: required
#dist: trusty

addons:
  - |
    if [ "$TRAVIS_OS_NAME" != "linux-ppc64le" ]; then
    chrome: stable
    fi

language: node_js

git:
  depth: 3
node_js:
  - "6"
  - "8"
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then sudo apt-get update && apt-get install -y libfontconfig ruby ruby-dev libffi6 libffi-dev curl; fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then wget https://github.com/ibmsoe/phantomjs/releases/download/2.1.1/phantomjs-2.1.1-linux-ppc64.tar.bz2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then bunzip2 phantomjs-2.1.1-linux-ppc64.tar.bz2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then tar -xvf phantomjs-2.1.1-linux-ppc64.tar; fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then cp phantomjs-2.1.1-linux-ppc64/bin/phantomjs /usr/bin/phantomjs; fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then curl -sSL https://rvm.io/mpapis.asc | gpg --import -; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then curl -sSL https://get.rvm.io | bash -s -- ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then /bin/bash -l -c "rvm install ruby-2.4 && rvm use ruby-2.4.1 "; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then /bin/bash -l -c "npm install -g grunt-cli && npm install phantomjs ";fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then /bin/bash -l -c "npm install phantomjs && npm install ";fi
  - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then /bin/bash -l -c "gem install bundle && bundle install "; fi
      
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install
after_success:
  - if [ "$TRAVIS_REPO_SLUG" = twbs-savage/bootstrap ]; then npm run docs-upload-preview; fi
stages:
  - test
  - name: browser
    if: type = push
jobs:
  include:
    - stage: browser
      node_js: 8
      script: if ! git log --format=%B --no-merges -n 1 | grep '\[skip browser\]'; then npm test && npm run js-test-cloud; fi
cache:
  directories:
    - node_modules
    - vendor/bundle
notifications:
  slack: heybb:iz4wwosL0N0EdaX1gvgkU0NH
  webhooks:
    - http://savage.twbsapps.com/savage/travis
